{% set version = "1.2.4" %}

package:
  name: pyside
  version: {{ version }}

source:
  fn: PySide-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/P/PySide/PySide-{{ version }}.tar.gz
  md5: 3cb7174c13bd45e3e8f77638926cb8c0
  patches:
    # eliminate spurious shiboken stderr output to avoid the 4MB log limit on Travis
    # https://codereview.qt-project.org/#/c/172582/
    - shiboken-osx-fix-stderr-output.patch
    # https://github.com/sparsehash/sparsehash/commit/7b8afad35bd601ea780b0f72e215de96613d3c95
    # https://codereview.qt-project.org/#/c/172583/
    - fix-vc2013-hash_map.patch
    # https://bugreports.qt.io/browse/PYSIDE-321
    # Backported https://code.qt.io/cgit/pyside/pyside.git/commit/?id=23d77136da1f249f0a78c8c7e8124adc8c604230
    - fix-vs2015-4.8.patch
    # make the testsuite pass
    - disable-failing-tests.patch
    # https://bugreports.qt.io/browse/PYSIDE-103
    - wrapinstance-overflow.patch

build:
  number: 7
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - toolchain
    - python
    - cmake
    - qt 4.8.*
    - libxslt
    - vc 9  # [win and py27]
    - vc 14  # [win and py>=35]
  run:
    - python
    - qt 4.8.*
    - libxslt
    - vc 9  # [win and py27]
    - vc 14  # [win and py>=35]

test:
  imports:
    - PySide.QtCore
    - PySide.QtDeclarative
    - PySide.QtGui
    - PySide.QtHelp
    - PySide.QtMultimedia
    - PySide.QtNetwork
    - PySide.QtScript
    - PySide.QtScriptTools
    - PySide.QtSql
    - PySide.QtSvg
    - PySide.QtTest
    - PySide.QtUiTools
    - PySide.QtWebKit
    - PySide.QtXml
    - PySide.QtXmlPatterns
    - PySide.QtOpenGL
    - PySide.phonon  # [not linux]
    - pysideuic
  commands:
    - pyside-lupdate -help
    - pyside-uic -help

about:
  home: https://wiki.qt.io/PySide
  license: LGPLv3
  license_file: sources/pyside/COPYING
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jschueller
    - ccordoba12
