travis:
  secure:
    BINSTAR_TOKEN: KTRHOSMV5JpzN00df+tXNk6ttqDtLOvj9pvoH8iUP1CRgZZuPqsQ4DXBxKqGzDeRieZJZyiY7Z2WfJ7/YBealnBW2QpoLSw2wKV13OJ6V3oE9z47sO4sw17lF2wBl+rELyqxPsA0AeKckZ1bKo1kgYg4Jnow8fnLXbJfDFHiHSvVbei5DTaKk6JWT9WPvZEvCQN/9Dp5MJMtQRkLysZQFngMVavMtYUT0zem8de+6OiBw/O6c47fWZFDfwJ8E5w3i88U0EkeMo71acSYz7kiqCJ8LtZlC7VM3+3W5FRONJ3kpNnnAZ/odncDEV0LMAt4KXKxe9oHnuuDEw3VcCQCDsCZPEB69kqeGYE4RfvsQLVvIIKcR3cUKpTwSYn+FAX7owXFJWL7ewDeb+QasjlZpKiJXSUoyJM9OuslXtFn/Qmp4uwDH5PPX9glBovsNe2KkrhuiZB1LJtZ6Vs/rQ4PmSGurVoXStkAflVg9ILnA60VWTt62AFQTUmm+nw5T+cilFs8j+fzujuSRF024/YmX+6tJ4QlAiqPLNTmjn8MHKnmUyTaD7izz79FduvDwr4mHtfiv0P/PUCuBRbftCBt/wsDLSQTxQA8dOLs9B0zMbhgfydrwBiMWWEhmXLqb8pZCOEQXmNYYTaYigpZJhv5QfsFug4jjQ2ZTW8ccJ8fB+c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
