travis:
  secure:
    BINSTAR_TOKEN: OOy/t6+vcotdapd5JawO7gDNmLsynisB6EftCkVeXURUyAwvXQ4OZjaLODQdVi4d1RsGFSoFerXT6Oa3ZiFgye5C5yAmIEX7peRLoKJYtce/1oHbeQgT2ht0EF9pTw9PL/VtxpF0YQmxwsLWkSDsdNgEUQXf13UYtgPwswalsL7V9YEvlzj0/Kx3hLcp30iKUFbAvc9E/Ry4OAVmKhb/nRth1aQDoZOlwhdfe/9nGkSyK8xAPsrrFBFe/nd7NRaKaHJOFWjs3OcbIeGOdhyBiCPJgDkCmKscH2j3EN9UMRT9D7Nk0/9WdDSk3jYuE16jxuStzn/ghHw9jOwO9tyykedu1HtYGd3qYeEGs62S51nlGnYneywksrdb/trsRoKAejnCvWOET2KV3+kBas1qW5eSWeXAc5Q/9s/iUrgjaEGx1BBO2QlQYajed93ipiBPqIdTL+t1hx75umxAy9LFiNPBY93KWxGu6JjCrlLiG4QK6BGw3QOF/XOnQmb06LD8+AYo+an9nD2SYgKpYsPA7PRL7HgAxMwoyK1zQYAjQWwI+9+QU7ni/9fOUpqV6g/adWhR83kWN12lHncuDYC++vWNZHLO/GyWB8hDqfmLdTRHYyJZDEbxm/scitJ60WsWkwx/WCL1gQ29XYVg9cvl6ehsJMgJIHa2tbDe78Fp++k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
